[package]
name = "image-colorizer"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories = ["multimedia::images", "graphics", "command-line-utilities"]

[[bin]]
name = "image-colorizer"
path = "src/main.rs"

[dependencies]
axum.workspace = true
anyhow.workspace = true
clap.workspace = true
config.workspace = true
dirs.workspace = true
futures.workspace = true
image.workspace = true
image-colorizer-core = { path = "../image-colorizer-core", version = "1.1.6" }
indicatif.workspace = true
palette.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_derive.workspace = true
tokio.workspace = true
toml.workspace = true
